### ISSUE TITLE
On "Press" Page, Add New GovTech Story at the Top

### ISSUE THREAD

**Issue by seamuskraft** [opengovfoundation/free-law-founders-site#11]
May 27, 2015 -- "Free Law Founders Make Strides for Open Government"

Link: http://www.govtech.com/data/Free-Law-Founders-Make-Strides-for-Open-Government.html

**Comment by krusynth** [comment]
For things this small, feel free to make the changes yourself directly, it's just as quick as adding an issue ticket:

https://github.com/opengovfoundation/free-law-founders-site/edit/gh-pages/press.md

:+1:
