### ISSUE TITLE
Open external links in new tab

### ISSUE THREAD

**Issue by cmbirk** [opengovfoundation/free-law-founders-site#6]
Using the press page as an example, add `target="_blank"` to the press links so that they can keep the main site open as they peruse other links.

**Comment by krusynth** [comment]
This is generally considered a bad practice for usability.  
- http://www.nngroup.com/articles/the-top-ten-web-design-mistakes-of-1999/
- http://www.nngroup.com/articles/top-ten-web-design-mistakes-of-2005/
- http://www.nngroup.com/articles/top-10-mistakes-web-design/
- http://www.l3s.de/~herder/thesis/

And so on.

**Comment by cmbirk** [comment]
@krues8dr Yeah, I can agree with that, at least for this use case and our audience.  Also would potentially cause problems on mobile.

It is a use-case basis though:

http://uxmovement.com/navigation/why-external-links-should-open-in-new-tabs/
http://ux.stackexchange.com/questions/54382/should-social-media-links-open-in-a-new-tab-or-window
